# Generated by Django 4.0.5 on 2022-07-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_merge_20220729_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medication',
            name='date',
            field=models.CharField(
                blank=True, default='2022-07-29', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.CharField(default='2022-07-29', max_length=30),
        ),
    ]
