# Generated by Django 4.0.5 on 2022-07-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_remove_serviserequest_status_myuser_isadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='price',
            field=models.IntegerField(default=50),
            preserve_default=False,
        ),
    ]
