# Generated by Django 4.0.5 on 2022-08-07 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_alter_serviserequest_reasonuser_and_more'),
        ('api', '0056_alter_medication_date_alter_messages_date'),
    ]

    operations = [
    ]
